services:
  # A Docker web service
  - type: web
    name: langflow
    runtime: docker
    dockerfilePath: ./docker/render.Dockerfile
    repo: https://github.com/aisprint/langflow
    branch: main
    plan: standard
    healthCheckPath: /health_check
    autoDeploy: true
    envVars:
      - key: LANGFLOW_DATABASE_URL
        value: postgresql://langflow_debv_user:0Ir3oeseO6xBPDvcmB4BBOnhWyB02fPH@dpg-ct3vc8rtq21c738vg5fg-a:5432/langflow_debv
      - key: LANGFLOW_HOST
        value: 0.0.0.0
      - key: LANGFLOW_PORT
        # default render port https://docs.render.com/web-services#port-binding
        value: ${PORT}
      - key: LANGFLOW_LOG_LEVEL
        value: INFO
    disk:
      name: langflow-data
      mountPath: /app/data
